version: '2'
services:
   snack-machine-service:
      build: Service/  
      container_name: snack-machine-service   
      volumes:
       - ./Service/:/opt/snack-machine
      ports:
        - "8000:8000"
   snack-machine-database:
      build: Database/
      container_name: snack-machine-database   
      volumes:
       - ./Database/data:/data/db
      ports:
        - "27017:27017"